name: Build and Deploy Electron App to S3

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install Dependencies
        run: npm ci

      - name: Package Electron App
        run: npx electron-forge package

      - name: Create Installers
        run: npx electron-forge make

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload Artifacts to S3
        run: |
          aws s3 sync out/make/ s3://lazy-rest-artifacts --exact-timestamps